version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/backend"
    assignees:
      - "louptheron"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/datascience"
    assignees:
      - "VincentAntoine"
    schedule:
      interval: "weekly"
    # Disable all dependencies update (hopefully)
    allow: []

  - package-ecosystem: "npm"
    directory: "/frontend"
    assignees:
      - "ivangabriele"
      - "louptheron"
    schedule:
      interval: "daily"
