version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/backend"
    assignees:
      - "louptheron"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/frontend"
    assignees:
      - "ivangabriele"
      - "louptheron"
    schedule:
      interval: "monthly"
