version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/backend"
    assignees:
      - "louptheron"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[Tech] "
    labels: ["tech. enhancement"]

  - package-ecosystem: "npm"
    directory: "/frontend"
    assignees:
      - "ivangabriele"
      - "louptheron"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[Tech] "
    labels: ["tech. enhancement"]
