version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - "ivangabriele"
      - "louptheron"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[Tech] "
    labels: ["tech. enhancement", "dependencies"]

  - package-ecosystem: "gradle"
    directory: "/backend"
    assignees:
      - "louptheron"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[Tech] "
    labels: ["tech. enhancement", "dependencies"]

  - package-ecosystem: "npm"
    directory: "/frontend"
    assignees:
      - "ivangabriele"
      - "louptheron"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[Tech] "
    labels: ["tech. enhancement", "dependencies"]

  - package-ecosystem: "pip"
    directory: "/datascience"
    assignees:
      - "VincentAntoine"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[Tech] "
    labels: ["tech. enhancement", "dependencies"]
