changelog:
  categories:
    - title: 🐛 Corrections
      labels:
        - bug
    - title: 👒 Dépendances
      labels:
        - dependencies
    - title: Toutes les PRs
      labels:
        - '*'
