version: "3"
services:
  db:
    container_name: monitorfish_database
    image: timescale/timescaledb-postgis:1.7.4-pg11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=monitorfishdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 30

  flyway:
    image: flyway/flyway
    command: migrate -password=postgres -schemas=public -user=postgres -url=jdbc:postgresql://db:5432/monitorfishdb
    volumes:
      - ../../backend/src/main/resources/db/:/flyway/sql
    depends_on:
      db:
        condition: service_healthy

  geoserver:
    image: kartoza/geoserver:2.18.0
    restart: unless-stopped
    ports:
      - 8081:8080
    links:
      - "db:db"
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    depends_on:
      db:
        condition: service_healthy

  geoserver-monitorenv-stubs:
    image: rodolpheche/wiremock
    ports:
      - 8081:8080
    volumes:
      - ./frontend/cypress/mappings:/home/wiremock/mappings

volumes:
  geoserver-data:
    driver: local
  db-data:
    driver: local
