services:
  monitorenv-db:
    image: docker.pkg.github.com/mtes-mct/monitorenv/monitorenv-database:pg11-ts1.7.4-postgis3.3.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=monitorenvdb
    volumes:
      - monitorenv-db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 30

  monitorenv-app:
    image: docker.pkg.github.com/mtes-mct/monitorenv/monitorenv-app:loup_add-mission-form-auto-save-and-update-refactoring
    container_name: monitorenv_backend
    environment:
      - ENV_DB_URL=jdbc:postgresql://monitorenv-db:5432/monitorenvdb?user=postgres&password=postgres
      - SPRING_PROFILES_ACTIVE=test
      - HOST_IP=127.0.0.1
      - REACT_APP_GEOSERVER_REMOTE_URL=http://0.0.0.0:8081
      - REACT_APP_GEOSERVER_NAMESPACE=monitorenv
      - REACT_APP_CYPRESS_TEST=true
      - REACT_APP_MISSION_FORM_AUTO_UPDATE=true
    ports:
      - 8882:8880
      - 8002:8000
      - 5002:5000
      - 5003:5001
    depends_on:
      - monitorenv-db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"

volumes:
  monitorenv-db-data:
    driver: local
