version: '3'
services:
  db:
    image: timescale/timescaledb-postgis:1.7.4-pg11
    container_name: monitorfish_database
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend
    restart: always

  app:
    image: docker.pkg.github.com/mtes-mct/monitorfish/monitorfish-app:$MONITORFISH_VERSION
    container_name: monitorfish_backend
    environment:
      - ENV_DB_URL=jdbc:postgresql://db:5432/$POSTGRES_DB?user=$POSTGRES_USER&password=$POSTGRES_PASSWORD
      - SPRING_PROFILES_ACTIVE=prod
      - HOST_IP=127.0.0.1
    ports:
      - 8880:8880
      - 8000:8000
      - 5000:5000
    networks:
      - backend
    depends_on:
      - db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"

networks:
  backend:

volumes:
  db-data:
    driver: local