name: "Build Application Docker Image"
description: "Build application Docker image."

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set version and environment profile
      uses: ./.github/actions/set-version-and-environment-profile

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache-app
        key: ${{ runner.os }}-app
        restore-keys: |
          ${{ runner.os }}-app

    - name: Build image
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        builder: ${{ steps.buildx.outputs.name }}
        file: infra/docker/app/Dockerfile
        push: false
        tags: monitorfish-app:${{ env.VERSION }}
        cache-from: type=local,src=/tmp/.buildx-cache-app
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-app-new
        build-args: |
          IS_RELEASE=false
          VERSION=${{ env.VERSION }}
          ENV_PROFILE=${{ env.ENV_PROFILE }}
          GITHUB_SHA=${{ github.sha }}
          SENTRY_URL=${{ secrets.SENTRY_URL }}
          SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG=${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }}

    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache-app
        mv /tmp/.buildx-cache-app-new /tmp/.buildx-cache-app
